/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardChart: typeof import('./src/components/dashboard/CardChart.vue')['default']
    IconRiArrowRightSLine: typeof import('~icons/ri/arrow-right-s-line')['default']
    IconRiBatteryLine: typeof import('~icons/ri/battery-line')['default']
    IconRiBlazeFill: typeof import('~icons/ri/blaze-fill')['default']
    IconRiCameraLine: typeof import('~icons/ri/camera-line')['default']
    IconRiChat1Line: typeof import('~icons/ri/chat1-line')['default']
    IconRiCloseCircleLine: typeof import('~icons/ri/close-circle-line')['default']
    IconRiCpuLine: typeof import('~icons/ri/cpu-line')['default']
    IconRiDashboardLine: typeof import('~icons/ri/dashboard-line')['default']
    IconRiDatabase2Line: typeof import('~icons/ri/database2-line')['default']
    IconRiDatabaseLine: typeof import('~icons/ri/database-line')['default']
    IconRiDeleteBinLine: typeof import('~icons/ri/delete-bin-line')['default']
    IconRiDoorLine: typeof import('~icons/ri/door-line')['default']
    IconRiDownload2Line: typeof import('~icons/ri/download2-line')['default']
    IconRiEqualizerLine: typeof import('~icons/ri/equalizer-line')['default']
    IconRiEraserLine: typeof import('~icons/ri/eraser-line')['default']
    IconRiEyeLine: typeof import('~icons/ri/eye-line')['default']
    IconRiEyeOffLine: typeof import('~icons/ri/eye-off-line')['default']
    IconRiFileCodeLine: typeof import('~icons/ri/file-code-line')['default']
    IconRiFileInfoLine: typeof import('~icons/ri/file-info-line')['default']
    IconRiFileLine: typeof import('~icons/ri/file-line')['default']
    IconRiFileList3Line: typeof import('~icons/ri/file-list3-line')['default']
    IconRiFlashlightLine: typeof import('~icons/ri/flashlight-line')['default']
    IconRiFolder6Line: typeof import('~icons/ri/folder6-line')['default']
    IconRiHomeLine: typeof import('~icons/ri/home-line')['default']
    IconRiInformationLine: typeof import('~icons/ri/information-line')['default']
    IconRiLightbulbLine: typeof import('~icons/ri/lightbulb-line')['default']
    IconRiLineChartLine: typeof import('~icons/ri/line-chart-line')['default']
    IconRiLockLine: typeof import('~icons/ri/lock-line')['default']
    IconRiMailLine: typeof import('~icons/ri/mail-line')['default']
    IconRiMapPinLine: typeof import('~icons/ri/map-pin-line')['default']
    IconRiMoreLine: typeof import('~icons/ri/more-line')['default']
    IconRiNotificationLine: typeof import('~icons/ri/notification-line')['default']
    IconRiOutletLine: typeof import('~icons/ri/outlet-line')['default']
    IconRiPlantLine: typeof import('~icons/ri/plant-line')['default']
    IconRiPlayCircleLine: typeof import('~icons/ri/play-circle-line')['default']
    IconRiPlugLine: typeof import('~icons/ri/plug-line')['default']
    IconRiPrinterLine: typeof import('~icons/ri/printer-line')['default']
    IconRiRamLine: typeof import('~icons/ri/ram-line')['default']
    IconRiRefreshLine: typeof import('~icons/ri/refresh-line')['default']
    IconRiSaveLine: typeof import('~icons/ri/save-line')['default']
    IconRiSearchLine: typeof import('~icons/ri/search-line')['default']
    IconRiSettings2Line: typeof import('~icons/ri/settings2-line')['default']
    IconRiShutDownLine: typeof import('~icons/ri/shut-down-line')['default']
    IconRiSnowflakeLine: typeof import('~icons/ri/snowflake-line')['default']
    IconRiSpeakerLine: typeof import('~icons/ri/speaker-line')['default']
    IconRiStickyNoteAddLine: typeof import('~icons/ri/sticky-note-add-line')['default']
    IconRiStopCircleFill: typeof import('~icons/ri/stop-circle-fill')['default']
    IconRiStopCircleLine: typeof import('~icons/ri/stop-circle-line')['default']
    IconRiTempColdLine: typeof import('~icons/ri/temp-cold-line')['default']
    IconRiTimerLine: typeof import('~icons/ri/timer-line')['default']
    IconRiTvLine: typeof import('~icons/ri/tv-line')['default']
    IconRiUpload2Line: typeof import('~icons/ri/upload2-line')['default']
    IconRiVideoOnLine: typeof import('~icons/ri/video-on-line')['default']
    IconRiWindyLine: typeof import('~icons/ri/windy-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceGPIO: typeof import('./src/components/service/ServiceGPIO.vue')['default']
    ServiceSettings: typeof import('./src/components/service/ServiceSettings.vue')['default']
    ServiceStorage: typeof import('./src/components/service/ServiceStorage.vue')['default']
    VIcons: typeof import('./src/components/ui/icons/VIcons.vue')['default']
  }
}
