/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlockScan: typeof import('./src/components/block/BlockScan.vue')['default']
    BlockService: typeof import('./src/components/block/BlockService.vue')['default']
    BlockStatus: typeof import('./src/components/block/BlockStatus.vue')['default']
    BlockUpdate: typeof import('./src/components/block/BlockUpdate.vue')['default']
    CardChart: typeof import('./src/components/dashboard/CardChart.vue')['default']
    IconRiArrowRightSLine: typeof import('~icons/ri/arrow-right-s-line')['default']
    IconRiChat1Line: typeof import('~icons/ri/chat1-line')['default']
    IconRiCpuLine: typeof import('~icons/ri/cpu-line')['default']
    IconRiDashboardLine: typeof import('~icons/ri/dashboard-line')['default']
    IconRiDatabase2Line: typeof import('~icons/ri/database2-line')['default']
    IconRiDeleteBinLine: typeof import('~icons/ri/delete-bin-line')['default']
    IconRiEqualizerLine: typeof import('~icons/ri/equalizer-line')['default']
    IconRiEraserLine: typeof import('~icons/ri/eraser-line')['default']
    IconRiEyeLine: typeof import('~icons/ri/eye-line')['default']
    IconRiEyeOffLine: typeof import('~icons/ri/eye-off-line')['default']
    IconRiFileCodeLine: typeof import('~icons/ri/file-code-line')['default']
    IconRiFileLine: typeof import('~icons/ri/file-line')['default']
    IconRiFolder6Line: typeof import('~icons/ri/folder6-line')['default']
    IconRiHomeLine: typeof import('~icons/ri/home-line')['default']
    IconRiInformationLine: typeof import('~icons/ri/information-line')['default']
    IconRiMailLine: typeof import('~icons/ri/mail-line')['default']
    IconRiMoreLine: typeof import('~icons/ri/more-line')['default']
    IconRiPlayLine: typeof import('~icons/ri/play-line')['default']
    IconRiPrinterLine: typeof import('~icons/ri/printer-line')['default']
    IconRiSaveLine: typeof import('~icons/ri/save-line')['default']
    IconRiSearchLine: typeof import('~icons/ri/search-line')['default']
    IconRiSettings2Line: typeof import('~icons/ri/settings2-line')['default']
    IconRiStickyNoteAddLine: typeof import('~icons/ri/sticky-note-add-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceGPIO: typeof import('./src/components/service/ServiceGPIO.vue')['default']
    ServiceSettings: typeof import('./src/components/service/ServiceSettings.vue')['default']
    ServiceStorage: typeof import('./src/components/service/ServiceStorage.vue')['default']
  }
}
